### ISSUE TITLE
Installation error: "dependency 'genderdata' is not available for package 'bibliographica'"

### ISSUE THREAD

**Issue by exsilica** [rOpenGov/bibliographica#6]
**Basics:** R Studio, R 3.3.1, OS X El Capitan
Attempting to replicate ["digital humanities lab" 2015 Paris workshop](http://ropengov.github.io/r/2015/06/12/Paris/) using /slides, /estc, and /bibliographica. 

1. Successfully cloned /slides
2. `render("20150612-Paris/20150611-Paris.Rmd")`
2a. `Error in library(estc) : there is no package called 'estc'`
3. `install_github("rOpenGov/estc")`
3a. `ERROR: dependency ‘bibliographica’ is not available for package ‘estc’`
4. `install_github("rOpenGov/bibliographica")`
4a. `ERROR: dependency ‘genderdata’ is not available for package ‘bibliographica’`
5. `install_github("rOpenGov/genderdata")`
5a. `Error in stop(github_error(request)) : Not Found (404)`

I did expect the 4a error as I did not find any such file in rOpenGov. I am at a loss as to where to go from here.

**Comment by antagomir** [comment]
The genderdata package is available from rOpenSci: https://github.com/ropensci/genderdata

We have made various changes to the estc & bibliographica packages (they are still in development) since the Paris workshop. I haven't checked whether the slides still run through without issues after the latest updates. Any reports welcome, we can make sure that it works if there is interest.
